// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ExtractDocument(arg1) {
  return window['go']['main']['App']['ExtractDocument'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportDocument(arg1) {
  return window['go']['main']['App']['ImportDocument'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
