// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2, arg3);
}

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function AppendSummary(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendSummary'](arg1, arg2, arg3);
}

export function ContentCopySelection() {
  return window['go']['main']['App']['ContentCopySelection']();
}

export function ContentEnsure() {
  return window['go']['main']['App']['ContentEnsure']();
}

export function ContentEval(arg1) {
  return window['go']['main']['App']['ContentEval'](arg1);
}

export function ContentLastURL() {
  return window['go']['main']['App']['ContentLastURL']();
}

export function ContentNavigate(arg1) {
  return window['go']['main']['App']['ContentNavigate'](arg1);
}

export function ContentRecreateAsPopup() {
  return window['go']['main']['App']['ContentRecreateAsPopup']();
}

export function ContentResize() {
  return window['go']['main']['App']['ContentResize']();
}

export function ContentSetChromeHeight(arg1) {
  return window['go']['main']['App']['ContentSetChromeHeight'](arg1);
}

export function ContentSetVisible(arg1) {
  return window['go']['main']['App']['ContentSetVisible'](arg1);
}

export function CreateLibraryFolder(arg1) {
  return window['go']['main']['App']['CreateLibraryFolder'](arg1);
}

export function EnsureSummary(arg1) {
  return window['go']['main']['App']['EnsureSummary'](arg1);
}

export function ExtractDocument(arg1) {
  return window['go']['main']['App']['ExtractDocument'](arg1);
}

export function FetchPageText(arg1) {
  return window['go']['main']['App']['FetchPageText'](arg1);
}

export function GoHome() {
  return window['go']['main']['App']['GoHome']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportDocument(arg1) {
  return window['go']['main']['App']['ImportDocument'](arg1);
}

export function LibraryRoot() {
  return window['go']['main']['App']['LibraryRoot']();
}

export function ListBookmarks(arg1) {
  return window['go']['main']['App']['ListBookmarks'](arg1);
}

export function ListLibraryFolders() {
  return window['go']['main']['App']['ListLibraryFolders']();
}

export function ListSummaries(arg1) {
  return window['go']['main']['App']['ListSummaries'](arg1);
}

export function MergeSummaryFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergeSummaryFiles'](arg1, arg2, arg3, arg4);
}

export function Navigate(arg1) {
  return window['go']['main']['App']['Navigate'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickLibraryFolder() {
  return window['go']['main']['App']['PickLibraryFolder']();
}

export function ReadSummaryFile(arg1) {
  return window['go']['main']['App']['ReadSummaryFile'](arg1);
}

export function RemoveBookmark(arg1) {
  return window['go']['main']['App']['RemoveBookmark'](arg1);
}

export function SetHomeURL(arg1) {
  return window['go']['main']['App']['SetHomeURL'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}

export function WriteSummaryFile(arg1, arg2) {
  return window['go']['main']['App']['WriteSummaryFile'](arg1, arg2);
}
