// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo():Promise<Record<string, string>>;

export function ExtractDocument(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportDocument(arg1:string):Promise<string>;

export function OpenFile():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
