// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBookmark(arg1:string,arg2:string,arg3:string):Promise<main.Bookmark>;

export function AppInfo():Promise<Record<string, string>>;

export function AppendSummary(arg1:string,arg2:string,arg3:string):Promise<main.SummaryRef>;

export function ContentCopySelection():Promise<void>;

export function ContentEnsure():Promise<void>;

export function ContentEval(arg1:string):Promise<void>;

export function ContentLastURL():Promise<string>;

export function ContentNavigate(arg1:string):Promise<void>;

export function ContentRecreateAsPopup():Promise<void>;

export function ContentResize():Promise<void>;

export function ContentSetChromeHeight(arg1:number):Promise<void>;

export function ContentSetVisible(arg1:boolean):Promise<void>;

export function CreateLibraryFolder(arg1:string):Promise<string>;

export function EnsureSummary(arg1:string):Promise<main.SummaryRef>;

export function ExtractDocument(arg1:string):Promise<string>;

export function FetchPageText(arg1:string):Promise<string>;

export function GoHome():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ImportDocument(arg1:string):Promise<string>;

export function LibraryRoot():Promise<string>;

export function ListBookmarks(arg1:string):Promise<Array<main.Bookmark>>;

export function ListLibraryFolders():Promise<Array<string>>;

export function ListSummaries(arg1:string):Promise<Array<main.SummaryRef>>;

export function MergeSummaryFiles(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SummaryRef>;

export function Navigate(arg1:string):Promise<void>;

export function OpenFile():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function PickLibraryFolder():Promise<string>;

export function ReadSummaryFile(arg1:string):Promise<string>;

export function RemoveBookmark(arg1:string):Promise<void>;

export function SetHomeURL(arg1:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WriteSummaryFile(arg1:string,arg2:string):Promise<void>;
